"""Index to tables

Revision ID: 099661743720
Revises: 
Create Date: 2024-11-01 11:59:22.726734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099661743720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.create_index('idx_availability_date', ['availability_date'], unique=False)
        batch_op.create_index('idx_availability_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.create_index('idx_booking_date_start', ['date_start'], unique=False)
        batch_op.create_index('idx_booking_package_id', ['package_id'], unique=False)
        batch_op.create_index('idx_booking_status', ['status'], unique=False)
        batch_op.create_index('idx_booking_tour_guide_id', ['tour_guide_id'], unique=False)
        batch_op.create_index('idx_booking_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.create_index('idx_characteristic_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_booking_id', ['booking_id'], unique=False)
        batch_op.create_index('idx_notification_is_read', ['is_read'], unique=False)
        batch_op.create_index('idx_notification_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('Review_Images', schema=None) as batch_op:
        batch_op.create_index('idx_review_images_rr_id', ['rr_id'], unique=False)

    with op.batch_alter_table('Reviews_Rating', schema=None) as batch_op:
        batch_op.create_index('idx_reviews_rating_rating', ['rating'], unique=False)
        batch_op.create_index('idx_reviews_rating_tour_guide_id', ['tour_guide_id'], unique=False)
        batch_op.create_index('idx_reviews_rating_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.create_index('idx_skill_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.create_index('idx_tour_package_name', ['name'], unique=False)

    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.create_index('idx_tour_guide_active', ['active'], unique=False)
        batch_op.create_index('idx_tour_guide_toperator_id', ['toperator_id'], unique=False)
        batch_op.create_index('idx_tour_guide_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.create_index('idx_tour_operator_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)
    
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('TourGuide', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_email')

    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.drop_index('idx_tour_operator_user_id')

    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.drop_index('idx_tour_guide_user_id')
        batch_op.drop_index('idx_tour_guide_toperator_id')
        batch_op.drop_index('idx_tour_guide_active')

    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.drop_index('idx_tour_package_name')

    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.drop_index('idx_skill_tguide_id')

    with op.batch_alter_table('Reviews_Rating', schema=None) as batch_op:
        batch_op.drop_index('idx_reviews_rating_user_id')
        batch_op.drop_index('idx_reviews_rating_tour_guide_id')
        batch_op.drop_index('idx_reviews_rating_rating')

    with op.batch_alter_table('Review_Images', schema=None) as batch_op:
        batch_op.drop_index('idx_review_images_rr_id')

    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_tguide_id')
        batch_op.drop_index('idx_notification_is_read')
        batch_op.drop_index('idx_notification_booking_id')

    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.drop_index('idx_characteristic_tguide_id')

    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.drop_index('idx_booking_user_id')
        batch_op.drop_index('idx_booking_tour_guide_id')
        batch_op.drop_index('idx_booking_status')
        batch_op.drop_index('idx_booking_package_id')
        batch_op.drop_index('idx_booking_date_start')

    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_index('idx_availability_tguide_id')
        batch_op.drop_index('idx_availability_date')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourGuide', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
